### ISSUE TITLE
boost::program_options

### ISSUE THREAD

**Issue by ekg** [JohnLangford/vowpal_wabbit#974]
I tried to build vw on ubuntu 15.10.

I started with:

```bash
sudo apt-get install libboost-program-options-dev libboost-python-dev
./autogen.sh
make
```

But it seems that I hadn't installed all the needed boost packages:

```
ar rcs libvw.a hash.o global_data.o io_buf.o parse_regressor.o parse_primitives.o unique_sort.o cache.o rand48.o simple_label.o multiclass.o oaa.o multilabel_oaa.o boosting.o ect.o autolink.o binary.o lrq.o cost_s
ensitive.o multilabel.o label_dictionary.o csoaa.o cb.o cb_adf.o cb_algs.o mwt.o search.o search_meta.o search_sequencetask.o search_dep_parser.o search_hooktask.o search_multiclasstask.o search_entityrelationtask
.o search_graph.o parse_example.o scorer.o network.o parse_args.o accumulate.o gd.o learner.o lda_core.o gd_mf.o mf.o bfgs.o noop.o print.o example.o parser.o loss_functions.o sender.o nn.o confidence.o bs.o cbify
.o topk.o stagewise_poly.o log_multi.o active.o active_cover.o kernel_svm.o best_constant.o ftrl.o svrg.o lrqfa.o interact.o comp_io.o interactions.o vw_exception.o vw_validate.o audit_regressor.o gen_cs_example.o
 cb_explore.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/include  -fPIC  -o vw main.o -L. -l vw -l allreduce 
-L /usr/local/lib -L /usr/lib -L /usr/lib/x86_64-linux-gnu -l boost_program_options -l pthread -l z
./libvw.a(parse_args.o): In function `parse_reductions(vw&)':
parse_args.cc:(.text+0x1ea1): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
./libvw.a(parse_args.o): In function `parse_diagnostics(vw&, int)':
parse_args.cc:(.text+0x2f00): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
parse_args.cc:(.text+0x3127): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
parse_args.cc:(.text+0x334d): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
./libvw.a(parse_args.o): In function `parse_output_preds(vw&)':
parse_args.cc:(.text+0x35bc): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
parse_args.cc:(.text+0x36ac): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
parse_args.cc:(.text+0x371f): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
parse_args.cc:(.text+0x377e): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
parse_args.cc:(.text+0x3854): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
parse_args.cc:(.text+0x3902): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
```

I'll document here if I figure it out. If it's something obvious hopefully we can update the docs.

**Comment by ekg** [comment]
Relevant: http://stackoverflow.com/questions/12179154/undefined-reference-to-boostprogram-optionsoptions-descriptionm-default-l

**Comment by ekg** [comment]
I have libboost_program_options.so.1.58.0

**Comment by trufanov-nok** [comment]
Could you do `make clean && make` and store whole build output somewhere like pastebin.com?

**Comment by ekg** [comment]
The problem is that autogen.sh was broken by 808f88c0189b1ca6dbfca7dd73b0161018855d08
```
➜  vowpal_wabbit git:(master) ✗ ./autogen.sh
Boost at:  /usr/lib/x86_64-linux-gnu/libboost_program_options.so
Using --with-boost-libdir=/usr/lib/x86_64-linux-gnu
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `acinclude.d'.
libtoolize: copying file `acinclude.d/libtool.m4'
libtoolize: copying file `acinclude.d/ltoptions.m4'
libtoolize: copying file `acinclude.d/ltsugar.m4'
libtoolize: copying file `acinclude.d/ltversion.m4'
libtoolize: copying file `acinclude.d/lt~obsolete.m4'
Makefile.am:30: error: blank line following trailing backslash
```

I've attempted a fix at https://github.com/JohnLangford/vowpal_wabbit/pull/975.

**Comment by ekg** [comment]
As of #975 I get:

```
➜  vowpal_wabbit git:(master) ✗ ./configure 
....
checking for boostlib >= 1.0... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not find a version of the library!
```

So it still isn't resolved. Maybe configure needs a hint.

**Comment by JohnLangford** [comment]
Fix is merged now.

-John
