### ISSUE TITLE
failed build with Ubuntu 14.04 vowpal 8.0.5

### ISSUE THREAD

**Issue by downspot** [JohnLangford/vowpal_wabbit#1399]
Building from docker file from https://github.com/shabbychef/docker-vw

Worked fine with 8.0.4 but not 8.0.5, following error:

```
In file included from src/main/c++/jni_base_learner.cc:3:0:
src/main/c++/jni_base_learner.h:4:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
make[1]: *** [src/main/c++/jni_base_learner.o] Error 1
make: *** [install] Error 2
```

**Comment by arielf** [comment]
@downspot 

Thanks for the report.

Just trying to help here.  Looks like a change was made where you now need to have JAVA_HOME set in your environment to build vw (including the java API).

The following little bash script should be able to find JAVA_HOME for you (on Ubuntu/Debian at least):
```
#!/bin/bash

# Find the absolute path of the java executable
# follow all symlinks (to cover /etc/alternatives/java ...)

jpath=$(readlink -e $(which java))

if [[ "$jpath" != "" ]]; then
    while [[ "$jpath" != "/" ]]; do
        jpath=$(dirname $jpath)
        tryinc="$jpath/include"
        if [[ -d "$tryinc" ]]; then
            echo $jpath
            exit 0
        fi
    done
fi

echo "$0: Couldn't find home dir for java (JAVA_HOME)" 1>&2
echo "$0: Do you have java installed (developer headers included)?" 1>&2
exit 1
```

So if you have java (full, not just runtime) installed and you set:
```
    export JAVA_HOME=$(path_to_the_above_script)
```

You should be able to find the "jni.h" header under $JAVA_HOME/include and build.

Could you update the docker recipe?

**Comment by downspot** [comment]
Much thanks worked like a charm. Reference for anyone else having issues https://github.com/downspot/docker-vw
