### ISSUE TITLE
can't build in ubuntu 12.04 with g++ 4.8

### ISSUE THREAD

**Issue by fancyerii** [JohnLangford/vowpal_wabbit#582]
I want to build it in Ubuntu 12.04. the default g++ 4.6 can't support c++ 0x. So I update gcc/g++ to 4.8.
My boost version is 1.46

the error of make

/usr/include/c++/4.8/bits/stl_tree.h:140:49: error: use of deleted function 'constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::basic_string<char>; _T2 = boost::program_options::variable_value]'
    _M_value_field(std::forward<_Args>(__args)...) { }
                                                 ^
In file included from /usr/include/c++/4.8/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/4.8/bits/char_traits.h:39,
                 from /usr/include/c++/4.8/ios:40,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from global_data.cc:9:

**Comment by bscottm** [comment]
@fancyerii: You also have to rebuild Boost to match your compiler and compiler version. A Boost compiled against gcc 4.6 isn't going to work with gcc 4.8.

**Comment by JohnLangford** [comment]
I don't understand this bug.  My laptop is Ubuntu 12.04 with:

#g++ --version                               
g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

and everything compiles fine.   More info is need to debug any further.  (closing for now)
