### ISSUE TITLE
7.10 does not compile on mac os 10.8

### ISSUE THREAD

**Issue by zachmayer** [JohnLangford/vowpal_wabbit#523]
I'm trying to update the [version of vowpal wabbit in homebrew to 7.10](https://github.com/Homebrew/homebrew/pull/36910). (Homebrew is a super handy package manager for mac os X, and makes it a snap to install VW and all of it's dependencies correctly on a mac).

As part of their build process, they test the package on 10.8 (mountain lion), 10.9 (mavericks) and 10.10 (yosemite).  [The builds is failing on 10.8](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/21544/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_vowpal_wabbit/)

I was wondering if someone here could help me get VW to compile on mac os 10.8?  Thank you.

**Comment by zachmayer** [comment]
This appears to be some kind of weird cxx11 issue.  I've tried adding the `--enable-libc++` flag to the brew formula to no avail.  I'll post here if I have any luck fixing this.

**Comment by JohnLangford** [comment]
I looked at the jenkins build.  The critical error seems to be this:

In file included from cbify.cc:6:
./../explore/static/MWTExplorer.h:16:10: fatal error: 'tuple' file not found
#include <tuple>
         ^

This is not a c++11 issue---it's the compiler complaining that the 'tuple'
header file from STL is missing  (http://www.cplusplus.com/reference/tuple/).
The 'tuple' on my (linux) system is in:
/usr/include/c++/4.6/tuple

Where is tuple on OSX 10.8?

Incidentally, if you have a way to do automated builds on checkin for OSX
similar to the way that travis does
https://travis-ci.org/JohnLangford/vowpal_wabbit  that would be great.

-John

**Comment by zachmayer** [comment]
Agreed, I'm trying (through guess and check) to find which homebrew options fix this.  It has something to do with boost on 10.8 vs 10.9 and 10.10.

**Comment by JohnLangford** [comment]
<tuple> should not be dependent on boost.  It is a core feature of C++.

-John

**Comment by zachmayer** [comment]
Ahah!  Could this be some kind of c++11 issue? (This is all new territory for me, so I apologize if any of these questions are dumb)

**Comment by JohnLangford** [comment]
Yes, apparently.  <tuple> seems to barf on my system if --std=c++0x is not
enabled.

-John

**Comment by zachmayer** [comment]
Oddly enough, I was able to fix the problem by compiling both boost and vowpal wabbit with cxx11:
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/21618/

**Comment by JohnLangford** [comment]
On 02/19/2015 12:32 PM, Zach Mayer wrote:
>
> Oddly enough, I was able to fix the problem by compiling both boost 
> and vowpal wabbit with cxx11:
> http://bot.brew.sh/job/Homebrew%20Pull%20Requests/21618/
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnLangford/vowpal_wabbit/issues/523#issuecomment-75097253>.
>

Is there something that should go into the master branch to help with 
this issue?
-John

**Comment by zachmayer** [comment]
Hi John,

I don't think so.  I think the issue is something to do with clang on 10.8.  Sorry to bother you about it.

I'll have version 7.10 of VW in homebrew soon (hopefully this week?), which means mac users will be able to just `brew install vowpal-wabbit` to get the latest version.

Thanks,

Zach

**Comment by JohnLangford** [comment]
Cool, thanks.

-John
