### ISSUE TITLE
Can't build a Python library on Windows

### ISSUE THREAD

**Issue by arobinski** [JohnLangford/vowpal_wabbit#1342]
Hi! I am having problems building the Python vowpalwabbit library on Windows 10 64-bit. I get the following error:

```
c:\Programming\vowpal_wabbit\python> pip install -e .
Obtaining file:///C:/Programming/vowpal_wabbit/python
Installing collected packages: vowpalwabbit
  Running setup.py develop for vowpalwabbit
    Complete output from command C:\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Programming\\vowpal_wabbit\\python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing vowpalwabbit.egg-info\PKG-INFO
    writing dependency_links to vowpalwabbit.egg-info\dependency_links.txt
    writing top-level names to vowpalwabbit.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'vowpalwabbit.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info\SOURCES.txt'
    running build_ext
    error: [Errno 2] No such file or directory: 'C:\\Programming\\vowpal_wabbit\\python\\bin\\pyvw36.dll'

    ----------------------------------------
Command "C:\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Programming\\vowpal_wabbit\\python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Programming\vowpal_wabbit\python\
```

What can I do to build the library?

**Comment by JohnLangford** [comment]
I'm not sure.  @gramhagen any ideas?

**Comment by JohnLangford** [comment]
Or maybe @eisber knows?

**Comment by eisber** [comment]
maybe the wrong python version. Due to an issue with boost/python we only support 2.7 and 3.5

**Comment by arielf** [comment]
The error says anaconda python is being used. And later that the wrapper library `pyvw36.dll` isn't in place. OP might be able to resolve this by copying the missing `dll`s (if it exists anywhere) to a place where conda python expects to find them.  The critical thing to understand is that In order to be binary compatible, the python environment used (`conda`) must contain (or point-at/resolve-to) the exact versions of `libboost` and `libvw`, and the python API wrapper that `vw` itself was built against _and_  anything else that `vw` depends on.  Anaconda python is its own world (python virtual env) including packaging tools and a package manager that aren't standard. Perhaps a better approach is to ask conda developers to add support for `vw` and provide a `conda` package for it.

**Comment by sergeyf** [comment]
I am having a similar problem. It may be because `python35` and `python36` don't seem to be part of the Windows solution file `vw.sln`. After compiling, it builds `pyvw27.dll` but not the other two. Would it be possible to add the other two Python versions to the solutions file?

I tried the following and it errored out:
(1) Open `vw.sln` in Visual Studio.
(2) Try to add the `python35.vcxproj` and `python36.vcxproj` to the python folder and build.

Thank you all for the excellent package and the huge amount of work it takes!

**Comment by sergeyf** [comment]
Thanks @eisber. I installed `boost_1_65_1`, but the issue is still the same: when opening the sln file in Visual Studio 2015, the Python folder only has `python27` underneath it.

**Comment by eisber** [comment]
Did you upgrade all the packages?

Maybe you need to modify the post-build steps. Have a look at the csproj files.
And don’t forget the pip setup functions. I think it references the dlls too…

Markus

**Comment by sergeyf** [comment]
For posterity:

I manually replaced the string `1.63.0.0` with `1.65.1.0` in the six `.vcxproj` files that had boost versions and in `packages.config`, deleted the `packages` folder and reran `nuget`. 

However, a number of `1.63` packages were installed anyway. I am not sure why. Any ideas?

**Comment by JohnLangford** [comment]
I see the 1.63 dependency here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/vw_dynamic.vcxproj#L534

@eisber why is 1.65 required?

**Comment by eisber** [comment]
Because 1.65 links to the wrong boost-python binding. See https://github.com/JohnLangford/vowpal_wabbit/issues/1176#issuecomment-339797375

**Comment by JohnLangford** [comment]
@eisber upthread you said "Upgrading to boost 1.65 should solve it…" but here that 1.65 links wrong.  These seem contradictory?

**Comment by eisber** [comment]
I mixed the version. We are currently on boost 1.63 (which links to the wrong version) and according to Sergey upgrading to 1.65 should solve the issue.

Markus

**Comment by sergeyf** [comment]
I thought it fixed the issue, but I was never able to fully install VW Python for Windows.

**Comment by eisber** [comment]
I took a closer look and tried to upgrade myself. Unfortunately the issue is still not resolved. 

When looking at packages\boost_python3-vc140.1.65.1\lib\native\address-model-64\lib\boost_python3-vc140-mt-1_65_1.dll using Dependency Walker you'll see it still links against python27.dll

**Comment by eisber** [comment]
There's even an open issue: https://github.com/boostorg/python/issues/129

**Comment by suamin** [comment]
Hi,
I'm also trying to install the python wrapper with 3.5 but its not working. I followed all the steps discussed in this thread but didn't worked. However, the wrapper is working fine with Python 2.7 on windows. For 3.5, I added `windows35\python35.vcxproj` to `vw.sln` under `python` solution folder (besides `python27`)  to get `pyvw35.dll` under `python\bin` but I'm getting linker error `LNK1104 cannot open file 'python27.lib'` with `python35` which is odd but again as @eisber said, `packages\boost_python3-vc140.1.65.1\lib\native\address-model-64\lib\boost_python3-vc140-mt-1_65_1.dll` with dependecy walker shows link with `python27.dll` with error messages:
```
Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: A circular dependency was detected.
```
What are possible solutions to fix the problem and have the wrapper working with py3.5/3.6 (the command line usage of `vw.exe` and `pywv27.dll` are working fine), is the fix dependent on referenced Boost.Python issue [boostorg/python#129](https://github.com/boostorg/python/issues/129) or there are other possibilities? @eisber on #1176 [(comment)](https://github.com/JohnLangford/vowpal_wabbit/issues/1176#issuecomment-276386120)  you mentioned about building with 3.5, was it successful, if so please would share your steps.
Thank you.

**Comment by eisber** [comment]
I believe it’s dependent on boost. So there are the following options:


  *   Upgrade boost and hope it’s fixed in the latest Windows built
  *   Rebuilt boost yourself and use those binaries
  *   Re-implement python VW bindings w/o using boost-python

Markus

**Comment by suamin** [comment]
Thanks for the suggestions, I just upgraded to boost 1.66.0.0 but still getting same linker error about `python27.lib` with `python35`. 

```
dumpbin /dependents boost_python3-vc140-mt-gd-x64-1_66.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file boost_python3-vc140-mt-gd-x64-1_66.dll

File Type: DLL

  Image has the following dependencies:

    python27.dll
    MSVCP140D.dll
    KERNEL32.dll
    VCRUNTIME140D.dll
    ucrtbased.dll

  Summary

        3000 .data
        1000 .gfids
        D000 .pdata
       2C000 .rdata
        1000 .reloc
        1000 .rsrc
       5E000 .text
        1000 .tls
```
I think the problem with Boost.Python still persists and probably rebuilding boost will not help either (check Stefan's post [here](https://lists.boost.org/boost-build/2017/12/29715.php)).

**Comment by JohnLangford** [comment]
Thanks @suamin 

This seems to be fairly conclusive evidence the VW+Python-3.5+Windows problem is in the boost python library and unresolved.   

I'm going to close this for now as I'm not able to fix the issue.

**Comment by aazim-lakhani** [comment]
> pyvw36

Which version of libboost and libvw were used to build VW ?

**Comment by aazim-lakhani** [comment]
> Which version of libboost and libvw were used to build VW ?

**Comment by eisber** [comment]
1.63 see https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/cs/cli/vw_clr.vcxproj#L200
